# Path to word embeddings
embeddings: data/collobert/embeddings50.txt

# Path to train and test sentence pairs and labels
dataset: data/task1/MSRvid

# Max number of epochs
epochs: 40

# Word labels type:
#  - int - labels are one-hot (rounded to closest integer)
#  - approx - labels are approximated between two closest integers

label_rounding: approx

# Model specification:
model: cnn_1d
sentence_length: 30

input_type: sentence
